import searc from '../public/icon/Component_32.png';
import filt from '../public/icon/Component_39.png';
import fav from '../public/icon/favorite.png';
import hert from '../public/icon/heart.png';
import hm from '../public/icon/home.png';
import lg from '../public/icon/logout.png';
import msg from '../public/icon/message.png';
import nt from '../public/icon/notification.png';
import pf from '../public/icon/profile.png';
import set from '../public/icon/setting.png';
import img1 from '../public/artistic/pexels-ali-pazani.png';
import img2 from '../public/artistic/pexels-anastasia-shuraeva.png';
import img3 from '../public/artistic/pexels-andrea-piacquadio.png';
import img4 from '../public/artistic/pexels-antoni-shkraba.png';
import img5 from '../public/artistic/pexels-antoni-shkraba (2).png';
import img6 from '../public/artistic/pexels-ekaterina.png';
import img7 from '../public/artistic/pexels-genaro-servín.png';
import img8 from '../public/artistic/pexels-humphrey-muleba.png';
import img9 from '../public/artistic/pexels-pixabay.png';
import img10 from '../public/artistic/pexels-steve-johnson.png';

export const search = searc;
export const filter = filt;
export const favorite = fav;
export const heart = hert;
export const home = hm;
export const message = msg;
export const logout = lg;
export const notification = nt;
export const profile = pf;
export const setting = set;
export const icon1 = img1;
export const icon2 = img2;
export const icon3 = img3;
export const icon4 = img4;
export const icon5 = img5;
export const cover1 = img6;
export const cover2 = img7;
export const cover3 = img8;
export const cover4 = img9;
export const cover5 = img10;
